import {
  Box,
  Container,
  Grid,
  ImageList,
  ImageListItem,
  Stack,
  Typography,
} from "@mui/material";
import React from "react";
import dynamic from "next/dynamic";
const Navbar = dynamic(() => import("@/component/shared/Navbar/Navbar"), {
  ssr: false,
});
const Footer = dynamic(() => import("@/component/shared/Footer/Footer"), {
  ssr: false,
});
import Head from "next/head";
import PrivacyContent from "../src/component/privacy/privacyContent/PrivacyContent";
import BaseWhatsappButton from "@/component/reuseable/baseWhatsappButton/BaseWhatsappButton";
import Link from "next/link";

function Contato({
  loginOpen,
  setLoginOpen,
  handleLoginOpen,
  handleLoginClose,
}) {
  return (
    <div>
      <Head>
        <title>Lokkan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/negotiate.png" />{" "}
      </Head>

      <main className="section">
        <Navbar
          shape={false}
          paddingY={"1vh"}
          loginOpen={loginOpen}
          setLoginOpen={setLoginOpen}
          handleLoginClose={handleLoginClose}
          handleLoginOpen={handleLoginOpen}
          language="pt"
          myValue="pt"
          colorLogo
        />
        <Grid
          container
          direction="column"
          justifyContent="center"
          alignItems="center"
          sx={{
            height: { xs: "25vh", sm: "25vh", md: "25vh" },
            // width: { xs: "120%", sm: "120%", md: "100%" },
            background: "linear-gradient(90deg, #20BAF6 0%, #7450F0 100%)",
          }}
        >
          <Box
            sx={{
              position: { lg: "absolute", xl: "absolute" },
            }}
          ></Box>
        </Grid>

        <Box
          sx={{
            px: { xs: 2, sm: 2, md: 2, lg: 25, xl: 25 },
            position: { lg: "relative", xl: "relative" },
            top: -120,
          }}
        >
          <PrivacyContent name="Contato">
            <Typography mt={4} mb={2} variant="h6">
              Lokkan: Sua jornada tecnológica para seu novo imóvel começa agora!
            </Typography>
            {/* <Typography variant="h5" sx={{ fontWeight: 800 }}>
              Lokkan: Sua jornada tecnológica para seu novo imóvel começa agora!
            </Typography> */}
            <Typography variant="p">
              Descubra um universo de possibilidades e realize seus sonhos com a
              Lokkan, a sua parceira completa no mercado imobiliário.
            </Typography>
            <Typography variant="h5" sx={{ fontWeight: 800 }}>
              Na Lokkan, você encontra:
            </Typography>
            <ul>
              <li>
                <Typography variant="p">
                  Tecnologia de ponta: Plataforma online completa, busca
                  inteligente, visitas virtuais imersivas, assinatura digital e
                  muito mais para tornar sua experiência mais prática, rápida e
                  segura.
                </Typography>
              </li>
              <li>
                <Typography variant="p">
                  Diferenciais exclusivos: Compra garantida, maior comissão do
                  mercado, anúncios ilimitados e processo 100% digital para
                  garantir a sua tranquilidade e o seu sucesso.
                </Typography>
              </li>
              <li>
                <Typography variant="p">
                  Atendimento personalizado: Uma equipe de especialistas
                  experientes e apaixonados por realizar sonhos, prontos para te
                  guiar em cada etapa da sua jornada.
                </Typography>
              </li>
              <li>
                <Typography variant="p">
                  Compromisso com a sua felicidade: Acreditamos que a casa dos
                  seus sonhos é a chave para a sua realização pessoal, e por
                  isso, trabalhamos incansavelmente para te entregar o imóvel
                  perfeito para você.
                </Typography>
              </li>
            </ul>
            <Typography variant="h5" sx={{ fontWeight: 800 }}>
              Dê o primeiro passo para o seu novo imóvel!
            </Typography>
            <Typography variant="p">Entre em contato conosco:</Typography>

            <Typography variant="p">Muito obrigado,</Typography>

            <Typography variant="p" sx={{ fontWeight: 600 }}>
              Equipe Lokkan
            </Typography>

            <Box sx={{ width: "10%", py: 1 }}>
              <BaseWhatsappButton />
            </Box>

            <Typography variant="p">atendimento@lokkan.com.br</Typography>
            <Link href="https://www.lokkan.com.br">
              <a target="_blank">www.lokkan.com.br</a>
            </Link>
          </PrivacyContent>
        </Box>

        <Footer />
      </main>
    </div>
  );
}

export default Contato;
